org: '1256505457'
app: node-server-test
stage: dev
component: koa
name: koa-EhFm5bWyQ
inputs:
  src:
    src: ./
    exclude:
      - .env.local
      - docs
      - build
      - _tests_
      - .github
      - src
      - .eslintrc.json
      - jest.config.ts
  region: ap-chengdu
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
    serviceTimeout: 60
    autoCreateDns: false
  isAutoCiDeploy: false
  functionConf:
    eip: true
    timeout: 10
    memorySize: 128
    environment:
      variables:
        NODE_ENV: test
  layers:
    - name: '${output:${stage}:${app}:node-server-test-layer.name}'
      version: '${output:${stage}:${app}:node-server-test-layer.version}'
